[package]
name = "xenon"
version = "0.1.0"
authors = ["Kaz Wesley <kaz@lambdaverse.org>"]

[dependencies]
failure = { version = "0.1", default-features = false }
typenum = { version = "1.10", features = ["no_std"] }
